-- Create the table for storing daily news summaries
create table if not exists news_summaries (
  date date primary key,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table news_summaries enable row level security;

-- Create table for error logs (System Monitoring)
create table if not exists error_logs (
  id bigint generated by default as identity primary key,
  source text not null, -- e.g., 'scraper:cnyes', 'api:gemini'
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for logs
alter table error_logs enable row level security;
